### PR TITLE
Py-chemshell plugin

### PR DESCRIPTION
**Pull request by chemsh**
- [x] Development of a tool plugin for Py-ChemShell has been basically done
- [x] It didn't involve any code change to the Aten kernels but only io_chemshell and tool_chemshell
- [x] Added both CMake and autotools ways of compile
NB: This plugin depends on io_chemshell because I find tool plugin interface can hardly access I/O (I may be wrong) and the current tool needs to write out new .pun files, but this shouldn't be a problem.

### CODE REVIEW

**Comment by trisyoungs** [comment]
Looks like you used the CMake build system.  Can you add autotools (Makefile.am) stuff for it too?

**Comment by chemsh** [comment]
Hi Tristan,


sure, will add it. I'll let you know when I'm ready for the pull request.


Many thanks.


You

________________________________

**Comment by chemsh** [comment]
Done that. Tested to be working. Thank you.

**Comment by trisyoungs** [comment]
Looks good! Merged and closed.

**Pull request merged**
